# ── Font
font_family IosevkaTerm Nerd Font Mono
font_size 20

# ── Colors
foreground #c5c9c8
background #080a0a
cursor #aeb7b3

color0  #101313
color8  #45504c

color1  #25282a
color9  #806f75

color2  #303833
color10 #718276

color3  #3d423e
color11 #8a8b72

color4  #3a4147
color12 #6e7f8a

color5  #48454c
color13 #7b7180

color6  #465354
color14 #788b8a

color7  #b9bfbd
color15 #a5aaa5

# ── Selection
selection_background #3d423e
selection_foreground none

# ── Window & cursor
cursor_blink_interval 0
window_padding_width 10

# ── Behavior
scrollback_lines 10000
enable_audio_bell no
